# <center> Exercise 4 Multilayer Perceptron Implementation </center>

<span style="background: yellow"><b>Edits</b></span>:
<ul>
    <li><span style="background: yellow"> v2 (May 18): Edits in documentation of 5.2. and 5.3., fixed target values in test case of 5.3.</span>
    <li><span style="background: yellow"> v3 (May 19): Test case of 6.2: Random seed should be 42, not 6</span>
</ul>

</br>
On this exercise, you are implementing a feedforward neural network from scratch to do the MNIST problem. This one is using <code>Numpy</code>. As an exercise for Backpropagation as you learned from the lecture, you should work through the derivation of the loss function to the weights or biases with pen and paper. 
</br>

We will try to modularize our neural network as it consists of $L$ layers. **Read the following description carefully, otherwise you would have problems implementing it later**. Each layer $l$ has a weight matrix $W^{(l)}$ with the size of $(n^{(l)}, n^{(l-1)})$ where $n^{(l)}$ is the number of neurons (outputs) of the layer $l$, a bias vector $b^{(l)}$ with the size of $(n^{(l)}, 1)$. Each layer $l$ has an activation function $f$. Each layer $l$ can be the last layer or not (the error term is calculated differently in that case). First, we will implement those parts for one layer:
    
* Initialize a layer: Use Xavier Initialization if the activation is sigmoid or tanh, otherwise use He Initialization. (This is already given in the code)
* Do the forward pass through the layer based on its activation function:
    *  $$ z^{(l)} = W^{(l)}\cdot a^{(l-1)} + b^{(l)} $$
        $$ a^{(l)} = f(z^{(l)}) $$
    *  Where:<br/>
        $z^{(l)}$: intermediate net output of layer $l$<br/>
        $a^{(l)}$: activation of layer $l$, is the input of the next layer $l+1$, $a^{(0)} = X$<br/>
* Do the backward pass through the layer. Using the convenient notation $\check{w} = \frac{\partial \mathcal{L}}{\partial w}$ (in the code, $\check{w}$ is denoted by dw):<br/>
$$\check{w}^{(l)} = \check{a}^{(l)} \frac{\partial a^{(l)}}{\partial z^{(l)}}\frac{\partial z^{(l)}}{\partial w^{(l)}}= \check{a}^{(l)}f^{(l)'}a^{(l-1)}$$
* Update the weights/biases based on the gradient descent principle.

Then training the network is divided into several steps:
* Initialize the whole network (by initilizing every layer)
* Split training data into minibatches.
* Iteratively do following steps in $E$ epochs:
    * Shuffle minibatches.
    * Do the forward pass.
    * Calculate the loss.
    * Do the backward pass.
    * Update weights.
    
With the trained model, perform inference steps on the test data.  
  

The implementation uses mini-batches, i.e. multiple input samples are aggregated into one tensor and passed through the forward and backward pass all at once. This means, if a single data sample is a vector $x \in R^n$, then the vectorized implementation has to work on inputs $x \in R^{n \times m}$, where $m$ is the batch size (in this exercise, we put the batch dimension at the end of the tensor). Thanks to `numpy`, such vectorized code often looks 
the same or very similar to the non-vectorized version.

First, let's import `numpy` and explore some basic methods: 

In [ ]:
import numpy as np


# 2. Implement basic activation functions (vectorized version)

__Sigmoid__:

In [ ]:
def sigmoid(z):
    # Your implementation here!
    pass

__Hyperbolic Tangent__:

In [ ]:
def tanh(z):
    # Your implementation here!
    pass

__Rectified Linear Unit (ReLU)__:

In [ ]:
def relu(z):
    # Your implementation here!
    pass

__Linear__:

In [ ]:
def linear(z):
    # Your implementation here!
    pass

__Softmax__:

In [ ]:
def softmax(z):
    # Your implementation here!
    pass
    

__Softmax for batch__:
</br>

Note that if we do minibatch update, we must compute the softmax along some dimension that is not the batch dimension. From our convention, batch dimension is the second (axis=1), so we must compute the softmax along the first dimension (axis=0).

In [ ]:
def softmax_batch(z, axis=0):
    # Your implementation here!
    pass

__Test your implementations__:

In [ ]:
np.random.seed(1234)
z = np.random.randn(100,2)

sigmoid_z = sigmoid(z)
tanh_z = tanh(z)
my_tanh_z = np.tanh(z)
relu_z = relu(z)
linear_z = linear(z)
softmax_z = softmax(z)


print("Sigmoid results of z[0]=%f, z[6]=%f, z[8]=%f, z[22]=%f, z[98]=%f" \
      %(sigmoid_z[0,0], sigmoid_z[6,0], sigmoid_z[8,0], sigmoid_z[22,0], sigmoid_z[98,0]))
print("Tanh results of z[3]=%f, z[9]=%f, z[18]=%f, z[34]=%f, z[99]=%f" \
      %(tanh_z[3,0], tanh_z[9,0], tanh_z[18,0], tanh_z[34,0], tanh_z[99,0]))
print("Relu results of z[8]=%f, z[16]=%f, z[38]=%f, z[72]=%f, z[88]=%f" \
      %(relu_z[8,0], relu_z[16,0], relu_z[38,0], relu_z[72,0], relu_z[88,0]))
print("Linear results of z[2]=%f, z[6]=%f, z[8]=%f, z[22]=%f, z[98]=%f" \
      %(linear_z[2,0], linear_z[6,0], linear_z[8,0], linear_z[22,0], linear_z[98,0]))
print("Softmax results of z[2]=%f, z[6]=%f, z[8]=%f, z[22]=%f, z[98]=%f" \
      %(softmax_z[2,0], softmax_z[6,0], softmax_z[8,0], softmax_z[22,0], softmax_z[98,0]))

__Your results should be__: <br/>
Sigmoid results of z[0]=0.615723, z[6]=0.721783, z[8]=0.599997, z[22]=0.561633, z[98]=0.459803 <br/>
Tanh results of z[3]=0.696046, z[9]=0.867072, z[18]=0.124070, z[34]=0.208769, z[99]=0.280640 <br/>
Relu results of z[8]=0.405453, z[16]=1.047579, z[38]=0.226963, z[72]=1.176812, z[88]=2.123692 <br/>
Linear results of z[2]=-0.720589, z[6]=0.953324, z[8]=0.405453, z[22]=0.247792, z[98]=-0.161137 <br/>
Softmax results of z[2]=0.001570, z[6]=0.008374, z[8]=0.004842, z[22]=0.004136, z[98]=0.002748 <br/>

# 3. Implement the derivations of basic activation functions 


__Sigmoid__:

In [ ]:
def sigmoid_prime(z):
    # Your implementation here!
    pass

__Tanh__:

In [ ]:
def tanh_prime(z):
    # Your implementation here!
    pass

__Rectified Linear Unit (ReLU)__:

In [ ]:
def relu_prime(z):
    # Your implementation here!
    pass

__Linear__:

In [ ]:
def linear_prime(z):
    # Your implementation here!
    pass

__Softmax__: 

This is hard to come up with without knowing the loss function. Most of the implementations out there are assuming we have cross entropy (or negative log likelihood) loss function. We will do the same, as the derivative of Softmax followed directly by Cross-Entropy Loss is far easier (see below). So, no need to implement Softmax derivative here. For your interest: https://eli.thegreenplace.net/2016/the-softmax-function-and-its-derivative/

This constrains the use of softmax to the last layer (where the loss function is applied directly on top of it), but that's fine for this exercise.

__Test your implementations__:

In [ ]:
np.random.seed(8888)
z = np.random.randn(100,1)

sigmoid_prime_z = sigmoid_prime(z)
tanh_prime_z = tanh_prime(z)
relu_prime_z = relu_prime(z)

print("Sigmoid prime results of z[2]=%f, z[6]=%f, z[8]=%f, z[22]=%f, z[98]=%f" \
      %(sigmoid_prime_z[2,0], sigmoid_prime_z[6,0], sigmoid_prime_z[8,0], sigmoid_prime_z[22,0], sigmoid_prime_z[98,0]))
print("Tanh prime of z[3]=%f, z[9]=%f, z[18]=%f, z[34]=%f, z[99]=%f" \
      %(tanh_prime_z[3,0], tanh_prime_z[9,0], tanh_prime_z[18,0], tanh_prime_z[34,0], tanh_prime_z[99,0]))
print("Relu prime results of z[8]=%f, z[16]=%f, z[38]=%f, z[72]=%f, z[88]=%f" \
      %(relu_prime_z[8,0], relu_prime_z[16,0], relu_prime_z[38,0], relu_prime_z[72,0], relu_prime_z[88,0]))


__Your results should be__: <br/>
Sigmoid prime results of z[2]=0.247928, z[6]=0.228343, z[8]=0.181437, z[22]=0.249350, z[98]=0.133364<br/>
Tanh prime of z[3]=0.027258, z[9]=0.928484, z[18]=0.357361, z[34]=0.621576, z[99]=0.568175<br/>
Relu prime results of z[8]=1.000000, z[16]=0.000000, z[38]=1.000000, z[72]=0.000000, z[88]=1.000000<br/>

# 4. Implement basic cost (error) function and its derivative


Note that we are going to calculate the error for a (mini)batch of $m$ training examples, which we assume they are [independent and identically distributed](https://en.wikipedia.org/wiki/Independent_and_identically_distributed_random_variables) (i.i.d), so the (normalized) total errors of those $m$ training examples (or $m$ data points) is $E = \frac{1}{m}\sum_{i=1}^mE^{(i)}$, where $E^{(i)}$ is an error value of the $i^{th}$ training example. However, in order to vectorize the error over a (mini)batch, we should come up with the direct version of error function of $E$ instead of $E^{(i)}$.

We implement Cross Entropy loss here, since we are trying to solve a classification problem with multiple classes (0-9). In the two class case, we could use Binary Cross Entropy, and for regression problems, Mean Squared Error, for instance. If you want to know more, look e.g. [here](https://ml-cheatsheet.readthedocs.io/en/latest/loss_functions.html).

__(Categorical) Cross Entropy Error__:

In [ ]:
def CrossEntropyError(t, y, epsilon=1e-15):
    # t: target label of shape(n,m)
    # y: predicted value of shape(n,m)
    
    # Your implementation here!
    pass


Hint: <b>Derivative of Cross Entropy</b><br/>
The cross entropy-function expects its input $y$ to be a normalized probability distribution (or a batch thereof). Thus, the activiation function directly before the loss (i.e. the last activation function of the network) is usually the softmax function. You could calculate the derivate $\frac{dL}{dy}$ and then $\frac{dy}{dz}$ step by step, where $L = CE(t, y)$ is the CE loss and $y = \text{softmax}(z)$. The input $z$ to the softmax is usually called the "logits". However, if you compute $\frac{dL}{dz}$ analytically, you can show the following simple formula:<br/>

$\frac{dL}{dz} = y - t$

You can implement this directly, just don't forget to properly handle the normalization due to the batched implementation.

In [ ]:
def dCE_dz(t, y):    
    # Your implementation here!
    pass

__Test your implementations__:

In [ ]:
# A handy helper function
def create_random_onehot(n, m):
    index = np.eye(n)
    return index[np.random.choice(index.shape[1], size=m)].T
t = create_random_onehot(3, 7)
print(t)

In [ ]:
# Test forward

np.random.seed(1111)
z = np.random.randn(100,50)
sum_z = np.sum(z, axis=0, keepdims=True)
y = z / sum_z # Create softmax-like distribution
t = create_random_onehot(100,50)

# Test forward
myCE = CrossEntropyError(t,y)
print("My Cross Entropy Error: " + str(myCE))


__Your results should be__: <br/>
My Cross Entropy Error: 15.8303339039 <br/>

In [ ]:
# Test backward

dCE_dz1 =  dCE_dz(t, z)
    
print("My Cross Entropy Derivation: dCE_dz at dCE_dz[2,4]=%f, dCE_dz[6,5]=%f, dCE_dz[8,20]=%f, dCE_dz[22,7]=%f, dCE_dz[98,40]=%f" \
      %(dCE_dz1[2,4], dCE_dz1[6,5], dCE_dz1[8,20], dCE_dz1[22,7], dCE_dz1[98,40]))

__Your results should be__: <br/>
My Cross Entropy Derivation: dCE_dz at dCE_dz[2,4]=-0.000196, dCE_dz[6,5]=0.020035, dCE_dz[8,20]=0.025941, dCE_dz[22,7]=-0.001366, dCE_dz[98,40]=0.013498

# 5. Layer Steps

## 5.1. Initialization

Initialize a layer: Use Xavier Initialization if the activation is sigmoid or tanh, otherwise use He Initialization.

In [ ]:
def initialize(n_in, n_out, activation_string):
    """
    Implement the initialization for our layer

    Arguments:
    n_in -- size of previous layer
    n_out -- size of current layer
    activation_string -- the activation to be used in this layer, stored as a text string: "sigmoid" or "relu"

    Returns:
    W -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    b -- bias vector, numpy array of shape (size of the current layer, 1)
    """
    
    if activation_string == 'sigmoid' or activation_string == 'tanh' or activation_string == 'softmax':
        # Xavier Initialization
        W = np.random.randn(n_out, n_in) * (np.sqrt(2. / (n_in + n_out)))
        b = np.zeros((n_out, 1))
    else: 
        # He Initialization
        W = np.random.randn(n_out, n_in) * (np.sqrt(1. / n_in))
        b = np.zeros((n_out, 1))
    return W, b

## 5.2. Forward pass

<span style="background: yellow"><b>Edit</b>:
    activation_string should be part of cache. The code documentation of 5.3. was also updated accordingly.
</span>

In [1]:
def forward(A_prev, W, b, activation_string):
    """
    Implement the forward propagation for our layer

    Arguments:
    A_prev -- activations from previous layer (or input data X): (size of previous layer, number of examples)
    W -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    b -- bias vector, numpy array of shape (size of the current layer, 1)
    activation_string -- the activation to be used in this layer, stored as a text string: "sigmoid" or "relu"

    Returns:
    A -- the output of the activation function, also called the post-activation value 
    cache -- values of (A_prev, Z, W, activation_string) we store for computing backward propagation efficiently
    """
    
    # Your implementation here!
    pass
    
    #return A, cache
    

__Test forward__:

In [ ]:
np.random.seed(2222)
A_prev = np.random.randn(3,2)
W = np.random.randn(1,3)
b = np.random.randn(1,1)

A, cache = forward(A_prev, W, b, "sigmoid")
print("With sigmoid: Z = %s , A = %s" % (str(cache[1]), str(A)))

A, _ = forward(A_prev, W, b, "tanh")
print("With tanh: A = " + str(A))

A, _ = forward(A_prev, W, b, "relu")
print("With ReLU: A = " + str(A))

A, _ = forward(A_prev, W, b, "softmax")
print("With softmax: A = " + str(A))

__Your results should be__: <br/>
With sigmoid: Z = [[ 1.1337088  -1.20334105]] , A = [[ 0.75652269  0.2308814 ]]<br/>
With tanh: A = [[ 0.81228478 -0.83467086]]<br/>
With ReLU: A = [[ 1.1337088  0.       ]]<br/>
With softmax: A = [[ 1. 1.]]

Can you explain why the softmax output is only ones?
What would have to be changed to get more "useful" values?

## 5.3. Backward pass

<b>Hint</b>: Keep in mind that, if the activation function is softmax, you can assume that dA is already dz (see the explanation for CE derivative above). This assumes that softmax is used only as the last layer of the network, but that is ok for this exercise.

<span style="background: yellow"><b>Edit</b>:
    activation_string is part of the cache. See 5.2. above.
</span>

In [ ]:
def backward(dA, cache):
    """
    Implement the backward propagation for our layer.
    
    Arguments:
    dA -- activation gradient for current layer l 
    cache -- values of (A_prev, Z, W, activation_string) we store for computing backward propagation efficiently, where
        activation_string is the activation to be used in this layer, stored as a text string: "sigmoid", "relu", "tanh" or "softmax"
    
    Returns:
    dA_prev -- Gradient of the cost with respect to the activation (of the previous layer l-1), same shape as A_prev
    dW -- Gradient of the cost with respect to W (current layer l), same shape as W
    db -- Gradient of the cost with respect to b (current layer l), same shape as b
    """
    
    # Your implementation here!
    pass
    
    #return dA_prev, dW, db


__Test Backward__:

In [ ]:
np.random.seed(1111)
dA = np.random.randn(1,2)
A_prev = np.random.randn(3,2)
W = np.random.randn(1,3)
b = np.random.randn(1,1)
Z = np.random.randn(1,2)

cache_sigmoid = (A_prev, Z, W, "sigmoid")
cache_tanh = (A_prev, Z, W, "tanh")
cache_relu = (A_prev, Z, W, "relu")
cache_softmax = (A_prev, Z, W, "softmax")

dA_prev, dW, db = backward(dA, cache_sigmoid)
print ("sigmoid:")
print ("dA_prev = "+ str(dA_prev))
print ("dW = " + str(dW))
print ("db = " + str(db) + "\n")

dA_prev, dW, db = backward(dA, cache_tanh)
print ("tanh:")
print ("dA_prev = "+ str(dA_prev))
print ("dW = " + str(dW))
print ("db = " + str(db) + "\n")

dA_prev, dW, db = backward(dA, cache_relu)
print ("relu:")
print ("dA_prev = "+ str(dA_prev))
print ("dW = " + str(dW))
print ("db = " + str(db) + "\n")

dA_prev, dW, db = backward(dA, cache_softmax)
print ("softmax:")
print ("dA_prev = "+ str(dA_prev))
print ("dW = " + str(dW))
print ("db = " + str(db))

__Your results should be__: <br/>
sigmoid:<br/>
dA_prev = [[ 0.38601836  0.4093035 ]<br/>
 [ 0.04975095  0.05275199]<br/>
 [ 0.37804364  0.40084773]]<br/>
<span style="background: yellow">dW = [[ 0.01722623 -0.1803237   0.09144594 ]]</span><br/>
db = [[-0.25163402]]<br/>
<br/>
tanh:<br/>
dA_prev = [[ 0.74460672  1.47719476]<br/>
 [ 0.09596665  0.19038431]<br/>
 [ 0.72922394  1.4466775 ]]<br/>
<span style="background: yellow">dW = [[ 0.22431658 -0.34262738  0.38665635]]</span><br/>
db = [[-0.70296173]]<br/>
<br/>
relu:<br/>
dA_prev = [[ 2.05442539  0.        ]<br/>
 [ 0.26477914  0.        ]<br/>
 [ 2.01198317  0.        ]]<br/>
<span style="background: yellow">dW = [[-0.51363355 -0.97619193 -0.17936819]]</span><br/>
db = [[-0.65000516]]<br/>

softmax:<br/>
dA_prev = [[2.05442539 1.69566033]<br/>
 [0.26477914 0.21854066]<br/>
 [2.01198317 1.66062981]]<br/>
dW = [[-0.04244893 -0.96335391  0.3390964 ]]<br/>
db = [[-1.18649968]]<br/>

## 5.4. Update parameters:

In [ ]:
def update_parameters(lr, W, b, dW, db):
    W1 = W - lr * dW 
    b1 = b - lr * db
    return W1, b1

# 6. Network Steps

## 6.1. Network Initialization

In [ ]:
def network_initialize(layer_sizes = [768,100,50,10], activations = ["relu","relu","softmax"], seed=9999):
    """
    Initialize the parameters of a network.
    
    Arguments:
    layer_sizes -- A list of layer sizes. 
    activations -- A list of corresponding activation functions.
    
    Returns:
    parameters -- Dictionary of initialized weights and biases for every layers.
    """
    
    np.random.seed(seed)
    
    # Your implementation here!
    pass
        
    #return parameters
        

In [ ]:
import pprint
parameters = network_initialize([2,3,4],["relu","softmax"])
pp = pprint.PrettyPrinter(indent=4)
pp.pprint(parameters)


__Your results should be__: <br/>
{ &nbsp;  &nbsp;  &nbsp;  &nbsp;    'W1': array([[-0.36418784, &nbsp;  &nbsp;  0.41853418], <br/>
  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;       [ 0.03385161, &nbsp;  &nbsp; -0.34535427], <br/>
   &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;      [-0.25098956, &nbsp;  &nbsp; -0.27705387]]), <br/>
 &nbsp;  &nbsp;  &nbsp;  &nbsp;    'W2': array([[ 0.99648945, &nbsp;  &nbsp; -0.73309211, &nbsp;  &nbsp;  1.18999424], <br/>
  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;       [-0.06313226,  &nbsp;  &nbsp; 0.06406165, &nbsp;  &nbsp;  0.09760321], <br/>
  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;      [-0.35157642, &nbsp;  &nbsp; -0.87994782, &nbsp;  &nbsp; -0.61020235], <br/>
  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;      [-0.76922564, &nbsp;  &nbsp;  0.39821514, &nbsp;  &nbsp; -0.92965227]]), <br/>
&nbsp;  &nbsp;  &nbsp;  &nbsp;    'act1': 'relu', <br/>
&nbsp;  &nbsp;  &nbsp;  &nbsp;     'act2': 'softmax', <br/>
&nbsp;  &nbsp;  &nbsp;  &nbsp;     'b1': array([[ 0.], <br/>
  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;      [ 0.], <br/>
  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;      [ 0.]]), <br/>
&nbsp;  &nbsp;  &nbsp;  &nbsp;   'b2': array([[ 0.], <br/>
  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;      [ 0.], <br/>
  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;      [ 0.], <br/>
  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;  &nbsp;      [ 0.]])} <br/>

## 6.2. Network Forward 

In [ ]:
def network_forward(X, parameters):
    """
    Do the forward pass through the layers.
    
    Arguments:
    X -- The input of the size (n, m): n features and m instances (m = batch size).
    parameters -- The weights and biases of every layers in the network.
    
    Returns:
    A -- Final activations (output activations).
    caches -- the cached values for faster calculation of the backward step later.
    """

    A_prev = X
    L = len(parameters) // 3 # Number of layers in the network
    caches = []
    
    for l in range(L):
        # Your implementation here!
        pass
    
    #return A, caches

In [ ]:
np.random.seed(42)
X = np.random.randn(5,4)
W1 = np.random.randn(4,5)
b1 = np.random.randn(4,1)
W2 = np.random.randn(3,4)
b2 = np.random.randn(3,1)
W3 = np.random.randn(3,3)
b3 = np.random.randn(3,1)
  
parameters = {"W1": W1,
              "b1": b1,
              "W2": W2,
              "b2": b2,
              "W3": W3,
              "b3": b3,
              "act1": "relu",
              "act2": "relu",
              "act3": "softmax"}
AL, caches = network_forward(X, parameters)    
print("AL = " + str(AL))



__Your results should be__: <pre>
AL = [[0.422804   0.04774435 0.01231299 0.3644841 ]
 [0.15449364 0.18041113 0.0384848  0.05945517]
 [0.42270236 0.77184451 0.94920221 0.57606073]]</pre>

## 6.3. Calculate the error and error term of the last layer 

In [ ]:
def calculate_error(T, AL, error_string):
    """
    Calculate the error and the error term of the last layer.
    
    Arguments:
    T -- The target labels of the size (n, m): n features and m instances (m = batch size).
    AL -- Final activations (output activations from the last layer).
    error_string -- The string representing the error function: "ce".
    
    Returns:
    error -- The error value.
    dAL -- the error term (the derivative of the error w.r.t the logits) of the last layer.
    """
    if error_string == 'ce':
        error = CrossEntropyError(T, AL)
        dAL = dCE_dz(T, AL)
    else:
        raise NameError("Your error string '%s' is undefined!" % error_string)
        
    return error, dAL
    

## 6.3. Network Backward

In [ ]:
def network_backward(dAL, caches):
    """
    Do the backward pass through the layers.
    
    Arguments:
    dAL -- the error term (the derivative of the error w.r.t the logits) of the last layer.
    caches -- the cached values from the forward step before.
   
    Returns:
    grads -- a dictionary to store the calculated derivatives of the error w.r.t to the weights and biases.
    """
    L = len(caches) # Number of layers in the network
    grads = {}
    
    dA = dAL
    
    for l in reversed(range(1,L+1)):
        # Your implementation here!
        pass
    
    #return grads

__Test your implementations__:

In [ ]:
np.random.seed(6)
X = np.random.randn(7,6)
W1 = np.random.randn(5,7)
b1 = np.random.randn(5,1)
W2 = np.random.randn(3,5)
b2 = np.random.randn(3,1)
W3 = np.random.randn(3,3)
b3 = np.random.randn(3,1)
  
parameters = {"W1": W1,
              "b1": b1,
              "W2": W2,
              "b2": b2,
              "W3": W3,
              "b3": b3,
              "act1": "relu",
              "act2": "sigmoid",
              "act3": "softmax"}

t = create_random_onehot(1,6)



AL, caches = network_forward(X, parameters)

print("My activation last layer AL:\n", AL)
error, dAL = calculate_error(t, AL, "ce")


print("========================")
print(" My error:" + str(error))

my_A2, my_Z3, _, _ = caches[2]

#my_dZ3 = dAL * sigmoid_prime(my_Z3)

my_dZ3 = dAL * softmax(my_Z3)
s = my_dZ3.sum(axis=my_dZ3.ndim - 1, keepdims=True)
my_dZ3 -= s * softmax(my_Z3) 



m = 1 # my_A2.shape[1]
my_dW3 = np.dot(my_dZ3, my_A2.T)
my_db3 = np.sum(my_dZ3, axis=1, keepdims=True)
my_dA2 = np.dot(W3.T, my_dZ3)


my_A1, my_Z2, _, _ = caches[1]
my_dZ2 = my_dA2 * relu_prime(my_Z2)
my_dW2 = np.dot(my_dZ2, my_A1.T)
my_db2 = np.sum(my_dZ2, axis=1, keepdims=True)
my_dA1 = np.dot(W2.T, my_dZ2)

my_A0, my_Z1, _, _ = caches[0]
my_dZ1 = my_dA1 * relu_prime(my_Z1)
my_dW1 = np.dot(my_dZ1, my_A0.T)
my_db1 = np.sum(my_dZ1, axis=1, keepdims=True)
my_dA0 = np.dot(W1.T, my_dZ1)


print("========================")
print("My W1 grad dW1:\n" + str(my_dW1)) 
print("My b1 grad db1:\n" + str(my_db1))


__Your results should be__: <pre>
My activation last layer AL:
 [[0.09088608 0.07286784 0.05814823 0.05320167 0.11602662 0.07744425]
 [0.14055201 0.12887469 0.09788826 0.07209716 0.03170778 0.08802502]
 [0.76856191 0.79825747 0.84396351 0.87470117 0.8522656  0.83453074]]
========================
 My error:5.247787227725874
========================
My W1 grad dW1:
[[-3.55816200e-03 -2.03557370e-02  2.62526818e-04  6.29708234e-04
  -1.58682250e-02 -6.07803260e-03  7.23596699e-03]
 [-4.12026165e-03  1.70212378e-03  3.21669546e-04  2.18363292e-03
   1.19729208e-03  1.92457456e-03  1.78100582e-03]
 [ 9.82892265e-05  4.11771156e-03 -6.45936229e-04  1.02518342e-03
   1.50412162e-03 -4.95592210e-03 -9.98074469e-03]
 [ 3.71604024e-03 -1.18149747e-03  2.67016538e-03  2.26150449e-03
  -8.44693518e-04 -5.23969785e-03 -6.96325589e-03]
 [ 4.52891773e-04  4.01409213e-04  6.15389899e-04  1.16153033e-03
   9.93284482e-04  3.40887741e-04 -6.78793063e-04]]
My b1 grad db1:
[[-0.01554985]
 [ 0.00288528]
 [ 0.0033295 ]
 [ 0.00676918]
 [ 0.0018925 ]]</pre>

# 6.4. Update the parameters:

In [ ]:
def network_update(lr, parameters, grads):
    """
    Update the parameters of all layers.
    
    Arguments:
    lr -- learning rate.
    parameters -- the parameters of the network to be updated.
    grads -- a dictionary to store the calculated derivatives of the error w.r.t to the parameters.
   
    Returns:
    parameters -- the updated parameters of the network.
    """
    
    L = len(parameters) // 3 # Number of layers in the network
    for l in range(L):
        # Your implementation here!
        pass
        
    return parameters

__Test your implementations__:

In [ ]:
np.random.seed(6)
X = np.random.randn(7,42)
W1 = np.random.randn(5,7)
b1 = np.random.randn(5,1)
W2 = np.random.randn(3,5)
b2 = np.random.randn(3,1)
  
parameters = {"W1": W1,
              "b1": b1,
              "W2": W2,
              "b2": b2,
              "act1": "relu",
              "act2": "softmax"}

t = create_random_onehot(3,42)


AL, caches = network_forward(X, parameters)
assert (np.sum(AL,axis=0) - 1.0 < 1e-7).all()
error, dAL = calculate_error(t, AL, "ce")
grads = network_backward(dAL, caches)

parameters = network_update(0.5, parameters, grads)

import pprint
pp = pprint.PrettyPrinter(indent=4)
pp.pprint(parameters)

__Your results should be__: <pre>
{   'W1': array([[-0.06433109,  0.10138926, -1.15591263, -0.68064486, -0.1148751 ,
         0.32687147, -0.16838151],
       [ 1.39317158,  0.74379015,  0.81427678, -1.75633047, -0.39980185,
         0.20249417, -0.37764711],
       [ 0.22868152, -0.56824287, -0.83499866, -0.04913708,  0.08748532,
        -0.29328866, -0.04104647],
       [ 0.96739929,  0.50522137,  0.81623356,  0.60461667,  0.11949221,
        -0.31723795,  1.84408903],
       [ 0.154503  ,  0.80559264, -0.58818036, -1.38825624, -1.18751226,
        -0.2753193 , -1.14249442]]),
    'W2': array([[-0.41547604,  2.71436799,  0.46541267,  0.14986723, -0.38547428],
       [ 1.30158278,  1.23631875, -2.34764109,  0.02390676,  0.32490526],
       [ 0.62120113, -1.22033908,  0.03224472,  1.77747704,  1.20463806]]),
    'act1': 'relu',
    'act2': 'softmax',
    'b1': array([[ 0.82798283],
       [-0.37387181],
       [-0.4301672 ],
       [ 1.65896485],
       [-0.31465256]]),
    'b2': array([[-0.92800218],
       [ 0.39610917],
       [-0.66433073]])}</pre>

# 7. Train MNIST

## 7.1. Read MNIST data

In [ ]:
data_path = "Data/mnist_seven.csv"
data = np.genfromtxt(data_path, delimiter=",", dtype="uint8")
train, dev, test = data[:4000], data[4000:4500], data[4500:]
print(train.shape)

## 7.2. Normalize data

In [ ]:
def normalize(dataset):
    X = dataset[:, 1:] / 255.     # Normalize input features
    Y_temp = dataset[:, 0]
    
    # Convert labels to one-hot vectors
    n_values = np.max(Y_temp) + 1
    Y = np.eye(n_values)[Y_temp]

    return X.T, Y.T

In [ ]:
X_train, Y_train = normalize(train)
print(X_train.shape)
print(Y_train.shape)

X_test, Y_test = normalize(test)
print(X_test.shape)
print(Y_test[:,5])

## 7.3. Training

In [ ]:
epochs = 100
batch_size = 200

# Train
print("Training...")
np.random.seed(1234)
parameters = network_initialize(layer_sizes = [784,100,50,10], activations = ["sigmoid", "sigmoid", "softmax"])


for epoch in range(epochs):
    L = 0
    
    # Split into minibatches into a *list* of sub-arrays
    # we want to split along the number of instances, so axis = 1
    X_minibatch = np.array_split(X_train, batch_size, axis = 1)
    Y_minibatch = np.array_split(Y_train, batch_size, axis = 1) 

    # We shuffle the minibatches of X and Y in the same way
    nmb = len(X_minibatch) # number of minibatches
    np.random.seed(8888)
    shuffled_index = np.random.permutation(range(nmb))

    # Now we can do the training, we cannot vectorize over different minibatches
    # They are like our "epochs"
    for i in range(nmb):
        X_current = X_minibatch[shuffled_index[i]]
        Y_current = Y_minibatch[shuffled_index[i]]         
            
    #   Those two commented lines are for training Batch GD   
    #   AL, caches = network_forward(X_train, parameters)
    #   error, dAL = calculate_error(Y_train, AL, "ce")
        AL, caches = network_forward(X_current, parameters)
        error, dAL = calculate_error(Y_current, AL, "ce")
        grads = network_backward(dAL, caches)
        parameters = network_update(15, parameters, grads)
        L += error
        
    print("Error of the epoch {0}: {1}".format(epoch + 1, L/batch_size))

print("...Done!")

## 7.4. Testing

In [ ]:
m_test = X_test.shape[1]
AL_test, _ = network_forward(X_test, parameters)
correct = (np.argmax(Y_test, axis=0) == np.argmax(AL_test, axis=0)).sum()
   
print('Accuracy on the test images: %d %%' % (100 * correct / m_test))

It should produce a 94% accuracy, which is not bad. Notice the learning rate. Change it and play with it. In our simple SGD-based model, it is an important hyperparameter and the performance of our model is learning rate-sensitive